name: github-actions
on:
  push:
    branches:
    # Limit to the `master` branch
    - master
jobs:
  github-actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run the workflow
      run: |
        set -e
        set -x
        # Configure Git for the push from the workflow to the repository
        git config --global user.email "tomas@hubelbauer.net"
        git config --global user.name "Tomas Hubelbauer"
        # Check out the `master` branch because by default GitHub Actions checks out detached HEAD
        git checkout master
        # Install Chromium dependencies needed on Ubuntu
        sudo apt update
        sudo apt install libgbm1 chromium-codecs-ffmpeg-extra -y
        # Capture the screenshots
        npm install
        node .
        # Authenticate with GitHub using the out of the box workflow integration PAT
        git remote set-url origin https://tomashubelbauer:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}
        # Add the screenshots to Git stage
        git add *-screenshot.png
        # Reset unstaged changes to prevent `git commit` from yelling if there's e.g. `package-lock.json` or caches
        git checkout -- .
        # Commit the added changes to the repository associated with this workflow (if any)
        if git diff-index --quiet HEAD --; then
          exit
        fi
        git commit -m "Commit the screenshots"
        # Rebase if the branch has meanwhile changed (fail if there are automatically irresolvable merge conflicts)
        git pull --rebase
        # Push the commit to the repository associated with this workflow
        git push
